### ISSUE TITLE
Optimize Refreshed ad support for mobile

### ISSUE THREAD

**Issue by georgebarnick** [Brickimedia/brickimedia#459] opened 2016-02-19 00:50 UTC
Currently, ads are restricted to 728x90 which is too large for proper mobile display and as a result are hidden. A small 320x50 ad placement for mobile would improve this and increase ad impressions by an estimated 90-100%

**Comment by mary-kate** [comment] 2016-02-19 06:52
Aye, mobile is big and likely getting just bigger, so adequate mobile support is a must; thankfully Refreshed is pretty mobile-friendly already. :)

For reference: Refreshed itself provides only the `RefreshedFooter` hook (currently line 469 of `Refreshed.skin.php`). The actual ad code resides in `LocalSettings.php`, lines 249-265 (which, if I may note, isn't the best place for it; either we should turn it into a mini-extension or merge into [ShoutWiki Ads](https://www.mediawiki.org/wiki/Extension:ShoutWiki_Ads) or somesuch). The problem is that line 256 hardcodes the `width` and `height` of the ad container element. Removing those and possibly defining the `data-ad-format` property for the element _should_ do the trick, I believe, but I'm not gonna lie: testing responsive ads is a huge pain.

**Comment by codynguyen1116** [comment] 2016-02-19 22:36
How does Google Ads prefer it? Instead of using inline styling, we can refer it to it's CSS class name, remove those inline styling, and use CSS media queries (at rules).

**Comment by mary-kate** [comment] 2016-02-20 11:02
Both solutions _should_ work equally well, although the only certain way is to try it out and see what happens. IMHO using the CSS class in Refreshed.css seems uglier in the way that technically speaking ad code isn't a part of the skin per se, so we'd be adding an unnecessary CSS rule for any and all non-Brickimedia sites using Refreshed which do not use (Google) ads.
Another possible solution would be to use Brickimedia's `MediaWiki:Global.css` page to implement CSS rules on the `adsbygoogle` class.

**Comment by codynguyen1116** [comment] 2016-02-21 04:51
Aye, I like that idea! :+1: This also allows wiki admins to change it, instead of just sysadmins. (better than [internal stylesheets too](https://support.google.com/adsense/answer/6307124?hl=en&ref_topic=1307438#exact))

**Comment by codynguyen1116** [comment] 2016-02-21 05:04
Wanted to comment on the placement/mini-extension thing: I have some questions, because I'm a curious person. :P 
- How difficult would it to be to make 'ShoutWiki Ads' non-ShoutWiki specific? We're on brickimedia's wikifarm setup instead of ShoutWiki's setup. 
- have you considered renaming 'ShoutWiki Ads' to something like 'SkinAdEmbed` (or something along the lines)? That name sounds better and less specific. Just a minor thing

**Comment by codynguyen1116** [comment] 2016-02-21 05:41
Added to MediaWiki:Global.css at meta on http://meta.brickimedia.org/wiki/Special:Diff/217071. Here's the code:
```css
@media (max-width: 500px) {
		.adsbygoogle {
			width: 320px;
			height: 50px;
	}
}

@media (max-width:799px) {
		.adsbygoogle {
			width: 480px;
			height: 60px;
		}
}

@media (min-width: 800px) {
		.adsbygoogle {
			width: 728px;
			height: 90px;
		}
}
```

**Comment by codynguyen1116** [comment] 2016-02-21 06:24
Oi so turns out this code is yucky for non-brickimedia wikifarms that use multiple skins. For skins that aren't refreshed, it'll just load some unnecessary code. We could use JS instead but it requires using `windows.matchMedia` which is only supported up to IE 10, it still uses ugly inline CSS, and it's more complicated than needed. Here's what it'd look like:
```javascript
var matchMediaArray = [ 
	window.matchMedia('(max-width: 500px)'), 
	window.matchMedia('(max-width: 799px)'), 
	window.matchMedia('(min-width: 800px)')
];

for (var i=0; i < matchMediaArray.length; i++){
    RefreshedGoogleAds(mqls[i]);
    matchMediaArray[i].addListener(RefreshedGoogleAds);
}

function RefreshedGoogleAds() {
	if( $(body).hasClass('.skin-refreshed')) {
		switch( window.MatchMedia(matchMediaArray).matches) {
			case matchMediaArray[0].matches:
				$('.adsbygoogle').css({'width' : '320px', 'height ': '50px'});
				block;
			case matchMediaArray[1].matches:
				$('.adsbygoogle').css({'width' : '480px', 'height' : '60px'});
				block;
			case matchMediaArray[2].matches:
				$('adsbygoogle').css({ 'width' : '728px', 'height' : '90px'});
		}
	};
}
```

**Comment by mary-kate** [comment] 2016-02-21 13:22
@codynguyen1116 [The documentation](https://www.mediawiki.org/wiki/Extension:ShoutWiki_Ads) is, as you'd guess, notoriously outdated (blame me). Seems that the code is also slightly oudated -- git.wm.o has version 0.3.3 whereas we're running v. 0.4.2 at ShoutWiki. I'll look into fixing these in the future, do poke me if I forget...

Anyway, despite the name, the extension's not _too_ ShoutWiki-specific. For MonoBook and Vector support, you need to patch those skins' main PHP files to add in the two hooks which are required. AdSense publisher ID, enabled slots per skin, etc. are fully configurable.
Adding Refreshed support to ShoutWiki Ads should be trivial enough (essentially merging the code that currently resides in Brickimedia's LocalSettings.php into the extension's PHP files).

As for the name, no, I haven't considered renaming it. Were it to be renamed, it'd require some careful thinking in order not to break anything at ShoutWiki. To be honest, I haven't seen it as a huge issue. The name isn't very creative, but it is what it is: ads by and for ShoutWiki (but the code just happens to run on most vanilla MWs with very little patching). It's not like it adds ugly crap to all pages or something like that. (In the past, at least some forum extensions for MediaWiki have had branding like "This forum provided by <extension> written by <developer's name>" or so; IMHO it's completely unnecessary since Special:Version is and has been a thing for over a decade.)

Good point re:unnecessary CSS. Maybe you could file an enhancement request on Phabricator and assign it to (or at least cc) @legoktm? It would certainly make sense to have stuff like `MediaWiki:Global-MonoBook.css` or `MediaWiki:Global-Refreshed.css` for wiki farms which support multiple skins (basically every MW wiki farm out there, save for Wikia), but the code needs to be thoroughly reviewed because the GlobalCssJs extension is used on Wikimedia.

**Comment by codynguyen1116** [comment] 2016-02-21 14:17
Hey, so apparently MediaWiki:Global-$skinname.jss/css has actually been a thing, in fact [exactly 2 years ago](https://gerrit.wikimedia.org/r/#/c/114896/). My apologies! :P 

(Accidentally created [phab.t.127647](https://phabricator.wikimedia.org/T127647) only to found after that [phab.t.63748](https://phabricator.wikimedia.org/T63748) already exists - oops)

We should be able to smoothly add the code to MediaWIki:Global-Refreshed.css without any bugs I think. I'll create that page on Meta

**Comment by legoktm** [comment] 2016-02-21 19:53
GlobalCssJs already supports skin-wide pages like MediaWiki:Global-refreshed.css.

**Comment by georgebarnick** [comment] 2016-02-21 20:00
Nice I've always just done an if (wgSkin) function in global.js good to know

**Comment by codynguyen1116** [comment] 2016-02-25 00:56
Fixed, closing

**Closed by codynguyen1116** 2016-02-25 00:56 UTC
Labels: [device] Phone, [improv] Optimization, [priority] Mid-high, [skin] Refreshed
