### ISSUE TITLE
Refreshed Icons replaced by Emoji on iOS

### ISSUE THREAD

**Issue by SirComputer1** [Brickimedia/brickimedia#468] opened 2016-03-04 07:07 UTC
On Chrome 48, iOS 9. I think the picture will say enough.

![image](https://cloud.githubusercontent.com/assets/5190450/13520308/448404a6-e1d7-11e5-9636-0f31b444a6f3.png)

**Comment by georgebarnick** [comment] 2016-03-04 07:08
Duplicate of #465

**Closed by georgebarnick** 2016-03-04 07:08 UTC
Labels: [general] Bug, [OS] iOS

**Comment by codynguyen1116** [comment] 2016-03-05 16:25
@SirComputer1 Check https://phabricator.wikimedia.org/T128604 if you're interested
