### ISSUE TITLE
Icons next to page actions in Refreshed

### ISSUE THREAD

**Issue by georgebarnick** [Brickimedia/brickimedia#369] opened 2015-04-09 18:58 UTC
On the page action toolbar, there should be icons next to each action (edit, delete, history, etc). They should use WikiFont icons as well (#344)

Via #274

**Comment by MtMNC** [comment] 2015-04-10 00:10
To do this we'll want to add in an empty span element with class .wikiglyph to each link. Unfortunately the makeLink function, which generates the page action links, doesn't have an argument that would let us do that. The function can take an element to wrap the link text in (as opposed to inserting a complete element at the beginning), but I don't think that's how WikiFont was intended to be used. Also, makeLink interprets the link contents as plain text instead of HTML, so we can't pass in the span as part of the link text. Does anybody have ideas on a clean way to do this? [Here's](https://doc.wikimedia.org/mediawiki-core/master/php/classBaseTemplate.html#a27f2b745a7253a37678d29ef3660fb00) some info on the makeLink class.

**Comment by codynguyen1116** [comment] 2016-02-07 19:52
Closing since we have WikiFont icons on mobile already

**Comment by georgebarnick** [comment] 2016-02-07 20:07
That's not what this issue was for. Go back to #274 and see the original page action link design had accompanying icons.

**Comment by codynguyen1116** [comment] 2016-02-07 20:13
Ah hmm looks easy enough, I'll try to push a commit for this today

**Comment by codynguyen1116** [comment] 2016-02-07 20:24
Nevermind it doesn't look so easy to be honest. :P I'll leave this for someone else to do

**Comment by MtMNC** [comment] 2016-02-07 21:41
IIRC Winter did that with CSS background images for each link instead of having actual icon elements in the HTML. Originally I was thinking we'd use HTML but CSS would probably be easier. Then if wikis used extensions that created new page actions (like WikiLove) the icons could be coded in with Refreshed.css.

**Comment by codynguyen1116** [comment] 2016-02-10 04:23
Sounds like a reliable method, go for it. (If I find some disadvantages worth mentioning vs images and as a glyph in a font later this week though I'll tell you)

**Comment by MtMNC** [comment] 2016-02-11 04:52
Will do when I have the time. (Maybe the long weekend?) In the meantime if anyone else wants to do this, go for it.

**Comment by MtMNC** [comment] 2016-02-14 21:55
Started working on this but I've run into some issues. Currently we use the WikiFont classes to add icons to the page. For example, each arrow in the page is an empty `span` with the class `.wikiglyph-caret-down`. The arrow shows up because the `.wikiglyph-caret-down:before` pseudo element is mapped to a specific symbol in the icon font. Like this:

```
<a><span class="wikiglyph wikiglyph-caret-down"></span>some link with a dropdown arrow</a>

.wikiglyph-caret-down:before {
  content: "\e053";
}
```

This means the end user can't (at least in a nice and clean way) change the icons in the header, since the `.wikiglyph-caret-down` element is part of the header HTML, which the user can't change. Changing the symbol from an arrow to something else would require overriding `.wikiglyph-caret-down:before` with CSS, which isn't a nice solution at all. That said, the current setup we have is fine for the header, since the icons probably won't ever need to be changed.

Not so for the page actions. I'm not sure if there's a clean way to add an empty `span` inside each individual page action link, but even if there is, it would mean the user couldn't easily change any of the page action icons. That's a problem given the variety of page actions: on top of the default ones, users might want to change icons for extensions, custom namespaces, and so forth.

The solution for the page actions would be to not use the WikiFont classes at all. It's easier to show you than to describe it. Instead of this:

```
<a id="ca-edit"><span class="wikiglyph wikiglyph-pencil"></span>edit</a>

.wikiglyph-pencil:before {
  content: "\e220";
}
```

We would do this:

```
<a id="ca-edit">edit</a>

#ca-edit:before {
  content: "\e220";
}
```

This is a cleaner solution since if the user wants to change the icon, they don't have to override the `.wikiglyph-pencil:before` class, which _only exists_ to make the pencil icon.

But it opens up another problem. The pencil character might be `U+E220` in this version of WikiFont, but in the next one it might be changed to another character, like `U+E221`. We can trust the `.wikiglyph-pencil` class will always be updated to point to the correct character, but if we stop using the WikiFont classes we'll have to change what class/id points to what character ourselves.

So yeah. Wha to do?

**Comment by codynguyen1116** [comment] 2016-02-15 03:15
I've been thinking for a while about what you said and still haven't quite come to a conclusion unfortunately, I'll try to get back to you tomorrow though :+1:

**Comment by georgebarnick** [comment] 2016-02-15 19:17
I think the cleaner solution will be fine. If WikiFont updates, we update. I don't think they'll change the numbers though at least not often

**Comment by MtMNC** [comment] 2016-02-21 05:09
Started working on this, but the header CSS broke when I updated the copy of WikiFont on my local clone to the latest version. That's because the old header CSS was really sloppy (totally my fault). Anyway the header looks the way it should now and the CSS is a lot cleaner to boot. WikiFont's been upgraded in the Refreshed repo as well. Now that everything's fixed, actually adding the icons shouldn't be too much of a problem.

**Comment by codynguyen1116** [comment] 2016-02-21 05:12
Ay, thanks MtMNC :) I saw your comment relating to vertically aligning images. I use these 3 magical lines of code to [vertically align them](http://zerosixthree.se/vertical-align-anything-with-just-3-lines-of-css/) and they always worked for me but we should test it just in case:

```css
element {
  position: relative;
  top: 50%;
  transform: translateY(-50%);
}
```

**Comment by codynguyen1116** [comment] 2016-02-21 05:15
Also, I saw you removed the lines relating to the psuedo placeholder element which made the search's input field `placeholder` bold, fixing one of the tasks in #434. Any reason you deleted that?

**Comment by MtMNC** [comment] 2016-02-21 05:21
@codynguyen1116 I tried that one but I think it only works when the height of the parent is defined. If you  move up the DOM tree from each image all the way up to `#header-wrapper` adding `height: inherit;` to each element you encounter along the way, it might work. Then you might run into issues with the avatar pushing the username and arrow down. It's a pain. It might be possible but it's a pain. :P

Actually the placeholder's still there, I just moved a bunch of properties around so all the header properties are together. It starts at line 281 now. :)

**Comment by codynguyen1116** [comment] 2016-02-21 05:32
Oi, too much maintenance! I'll look into more solutions that are cleaner for vertically-aligning images. :) (any reason why it's not so simple as adding `vertical-align: middle;` either? hmm..)

**Comment by MtMNC** [comment] 2016-02-21 05:37
Thanks. :)

I'm guessing `vertical-align: middle;` doesn't work because the "middle" of the line doesn't perfectly correspond to the "middle" of the actual text, since the actual text has descenders and ascenders that might not be the same height. Could be totally off though.

**Comment by MtMNC** [comment] 2016-02-22 06:02
Well I was gonna try and get this done today but I wasn't able to, sorry about that y'all. If anyone is up for it this week, go ahead, I probably won't have time until next weekend.

**Comment by MtMNC** [comment] 2016-02-28 05:20
Just added a bunch of icons. A few are still missing like icons for purge, related changes, logs, etc. but most of the important ones are there. Some of the other ones will require new WikiFont icons to be created.

**Comment by MtMNC** [comment] 2016-02-28 06:45
Huh. It looks like the version of WikiFont on Brickimedia isn't up to date with the version in the Brickimedia/Refreshed repo. Which character corresponds to which WikiFont icon seems to have changed between the old and current versions, so the icons don't match up properly with the page actions. Anyone know why the server's copy of WikiFont wouldn't match the newer one in the Refreshed repo?

**Comment by georgebarnick** [comment] 2016-02-28 08:33
Submodule hadn't been updated. Fixed

**Comment by codynguyen1116** [comment] 2016-02-28 17:21
Thanks @georgebarnick @MtMNC! Looks great :D :+1:

I'll push a commit to make it more readable and easier on the eye by increasing the font-size and weight by +100, and color etc etc and link it once that's done.

So now the main issue is deciding the icons for the more abstract actions (which is mentioned by you @MtMNC, although I still think we should focus on this):

# Rest of actions
* what links here
* page information
* related changes
* browse properties
* logs
* user rights management

# Suggestions
I have a couple suggestions, but most of them will require icon requests to be put into the WikiFont project.
* page information
  - ![image](https://cdn2.iconfinder.com/data/icons/app-types-in-grey/128/info_512pxGREY.png)
* browse properties - supposed to represent "data". Again, obscure, so maybe we should use the magnifying glass?
  - ![image](https://cdn2.iconfinder.com/data/icons/windows-8-metro-style/128/database.png) 
* user rights management
  - ![image](https://cdn0.iconfinder.com/data/icons/users-groups-1/512/user_settings-128.png)
* what links here - surprised there isn't an existing chain icon in the project. We could also use the paperclip link icon but that doesn't seem to make much sense..
  - ![image](https://cdn2.iconfinder.com/data/icons/windows-8-metro-style/128/link.png)

**Comment by codynguyen1116** [comment] 2016-02-28 17:34
Just remembered, we also configured Brickipedia with JS to show the inventory and review on set articles. What icons do we want for those?

**Comment by Edward-Nigma** [comment] 2016-02-28 22:13
@codynguyen1116 
The magnifying glass icon would make more sense for "browsing properties". 

However, the user rights icon doesn't seem right for its suggested use.

The chain icon makes more sense than a paperclips icon - paperclips are generally used to indicate attachments, more than anything.

**Comment by georgebarnick** [comment] 2016-02-28 22:15
i think those are fine

**Comment by codynguyen1116** [comment] 2016-02-28 22:24
OK so me and eddy talked about it on chat about the user rights icon and agreed that we'd use it because only admins and bureaus will be seeing it anyways.

So, user + cog, magnifying glass, and chain

**Comment by codynguyen1116** [comment] 2016-02-28 22:28
@georgebarnick @MtMNC @Edward-Nigma 

https://github.com/munmay/WikiFont/issues/45
https://github.com/munmay/WikiFont/issues/46
( and https://github.com/munmay/WikiFont/issues in general )


Make sure to add +1s to the icon requests :)

**Comment by MtMNC** [comment] 2016-02-28 23:03
IMO we shouldn't be using the magnifying glass for anything since it's already used as the search icon. One existing possibility is [.wikiglyph-article-search](https://github.com/munmay/WikiFont/blob/master/svgs/uniE102%20-%20articleSearch.svg), and another is [.wikiglyph-view-details](https://github.com/munmay/WikiFont/blob/master/svgs/uniE115%20-%20viewDetails.svg). There's a bunch of similar stripe/list icons we could use actually. We could use another one of them for "browse properties" (SMW) too.

Also we need a reload arrow icon for "purge."

**Comment by codynguyen1116** [comment] 2016-02-28 23:08
wait, i thought the refresh icon already existed :O time to put up a new icon request @https://github.com/munmay/WikiFont/issues/47 

There we go :) Article search icon looks good

**Comment by codynguyen1116** [comment] 2016-02-28 23:09
Any ideas for special pages, what links here, and related changes?

**Comment by MtMNC** [comment] 2016-02-28 23:19
Maybe [.wikiglyph-newspaper](https://github.com/munmay/WikiFont/blob/master/svgs/uniE241%20-%20newspaper.svg) or an icon based on it for related changes? As for the other two, I'm not sure. I was originally thinking [.wikiglyph-wikitrail](https://github.com/munmay/WikiFont/blob/master/svgs/uniE504%20-%20wikitrail.svg) for what links here, but I think that's actually a site logo so we'd best not be using it.

**Comment by codynguyen1116** [comment] 2016-02-28 23:25
wikiglyph-newspaper seems weird - looks more like for a newsletter or a blog. Also, I checked the wikimedia projects and wikitrail isn't used anywhere, so we should be fine

**Comment by Edward-Nigma** [comment] 2016-02-29 00:04
wikiglyph-newspaper seems more like it should be used for news articles or **recent** changes. It doesn't really suggest _related_ changes.

**Comment by neoncitylights** [comment] 2016-11-23 03:58
Superseded by https://phabricator.wikimedia.org/T151429

**Closed by neoncitylights** 2016-11-23 03:58 UTC
Labels: [improv] Enhancement, [skin] Refreshed
