### ISSUE TITLE
"Themes" dropdowns only appear in Refreshed

### ISSUE THREAD

**Issue by Edward-Nigma** [Brickimedia/brickimedia#390] opened 2015-05-09 06:42 UTC
The "themes" dropdowns that appear in the Refreshed headers appear only in Refreshed - they are not present in Vector, DeepSea, MonoBook, and god forbid anyone use Custard. I'm not sure if this was intended to only show up in Refreshed, but it would definitely be something nice to see in DeepSea/Vector/MonoBook.
![screen shot 2015-05-09 at 1 41 50 am](https://cloud.githubusercontent.com/assets/6055805/7549064/9efd28e0-f5ec-11e4-91d3-4e890a2606af.png)
![screen shot 2015-05-09 at 1 41 55 am](https://cloud.githubusercontent.com/assets/6055805/7549067/a8ba7bf8-f5ec-11e4-8ee2-2d8bedf4cbcd.png)

**Comment by codyn329** [comment] 2015-05-09 14:37
This was intended to be only in the refreshed menu, as implied in the name MediaWiki:Refreshed-navigation; I still agree though that it would be nice.

**Comment by georgebarnick** [comment] 2015-05-10 13:40
@Edward-Nigma: This is a feature exclusive to the Refreshed skin. Vector and Monobook are developed by Wikimedia and any such suggestions would need to be made at https://phabricator.wikimedia.org. DeepSea and Custard are both no longer developed for, so if you'd want something added to either, chances are you'd have to do it yourself.

**Comment by codynguyen1116** [comment] 2016-02-11 03:08
We don't manage Vector and would require hacks, and we also don't manage DeepSea, Quartz, Lia, or Custard anymore since they're retired skins basically so I'm closing this

**Closed by codynguyen1116** 2016-02-11 03:08 UTC
Labels: [improv] Enhancement, [skin] Custard, [skin] DeepSea, [skin] MonoBook, [skin] Refreshed, [skin] Vector
