### ISSUE TITLE
Special:GiveGift not working

### ISSUE THREAD

**Issue by LegoFan4000** [Brickimedia/brickimedia#470] opened 2016-03-19 16:29 UTC
Every time I try it doesn't work.

**Comment by mary-kate** [comment] 2016-03-19 21:05
`Special:GiveGift` and `Special:ViewGifts` are explicitly `unset()` in [LocalSettings_ext.php](https://github.com/Brickimedia/LocalSettings/blob/master/LocalSettings_ext.php), lines 79-80. I have no idea who did this or why, and the comments on those lines are stating the obvious rather than the reasoning behind this odd change.
In any case, I'd be more than happy to fix that since we're talking about an extremely simple two-line change to restore expected behavior. If someone objects to this change, I'd be _more_ than curious to hear a reason for such an objection.

**Comment by LegoFan4000** [comment] 2016-03-19 21:25
Yes please. Thanks.

**Comment by UltrasonicNXT** [comment] 2016-03-19 22:37
https://github.com/Brickimedia/brickimedia/issues/230

**Comment by LegoFan4000** [comment] 2016-03-19 23:13
If we don't it then remove the user page link

**Comment by mary-kate** [comment] 2016-03-20 13:56
#230 provides _some_ historical background into this matter, yet it still fails to answer the obvious question -- "why?". _Why_ are gifts "not used", _where_ and _when_ this decision was made and _by whom_? I'm strongly in favor of restoring default, expected SocialProfile behavior.
Users abusing the feature can be dealt with on a case-by-case basis, just like how you'd deal with any other vandalism case or somesuch -- just because one person abuses the edit feature doesn't mean you turn off the edit feature altogether.

**Comment by georgebarnick** [comment] 2016-03-20 19:51
IMO it's more work to add gifts and maintain them and to educate users about them than we have local administrators who aren't already filled to the brim with work to do. At some point there were discussions to minify the number of unessential features on the wiki and since no wiki had actually set up any gifts and didn't have any time to do so it was decided to scrap that feature.

**Comment by LegoFan4000** [comment] 2016-03-21 00:24
Seems like we are thinking about it. :P

**Comment by georgebarnick** [comment] 2016-03-21 04:40
http://en.brickimedia.org/wiki/Brickipedia:Forum#.28Re-.29Enabling_Gifts_.28and_more.21.29

**Comment by LegoFan4000** [comment] 2016-03-21 12:57
I saw and voted.

**Comment by neoncitylights** [comment] 2016-09-24 20:50
Discussed on Brickipedia, closing

**Closed by neoncitylights** 2016-09-24 20:50 UTC
Labels: [ext.group] Social Tools, [ext] SocialProfile, [general] Bug
